[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.youtube.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://justindonlon.com https://*.youtube.com https://i.ytimg.com data:; frame-src 'self' https://www.youtube.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; object-src 'none'; connect-src 'self';"
