[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' https://www.youtube-nocookie.com https://www.youtube.com;
  style-src 'self' 'unsafe-inline';
  img-src 'self' https:;
  frame-src 'self' https://www.youtube-nocookie.com https://www.youtube.com;
  font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
"""