[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = """
    default-src 'self' https: data: blob:;
    script-src 'self' 'unsafe-inline' https:;
    style-src 'self' 'unsafe-inline' https:;
    img-src 'self' https: data: blob:;
    frame-src https:;
    connect-src 'self' https:;
    font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
  """ """